Sqr calc
l0stg/kotlin_lab pull request #1
Opened 2022-06-26 18:07 UTC by l0stg

2022-06-26 18:14 UTC, Nyakit commented on app/src/main/java/com/example/helloworld/CalculateActivity.kt
> +//import kotlinx.android.synthetic.main.activity_main.*
Не оставляй закомменченный код, либо покрывай комментариями

2022-06-26 18:15 UTC, l0stg commented on app/src/main/java/com/example/helloworld/CalculateActivity.kt
> +//import kotlinx.android.synthetic.main.activity_main.*
Ок

2022-06-27 10:55 UTC, golovkinV requested changes

2022-06-27 10:55 UTC, golovkinV commented on app/src/main/java/com/example/helloworld/SqrCalc.kt
> +        fun CalcX (a:Double, b: Double, c: Double) {
CalcX -> calcX

2022-07-18 04:29 UTC, merged